use_thread: False
default_target: "dev"

target:
  dev:
    start_page: 1
    end_page: 3
    page_max: 54
    base_url: https://www.viettelidc.com.vn
    max_thread: 1
    data_raw_path: "raw_post/posts.json"
    limit_post: 10
  prod:
    start_page: 1
    end_page: 53
    page_max: 54
    base_url: https://www.viettelidc.com.vn
    max_thread: 1
    data_raw_path: "raw_post/posts.json"
    limit_post: 300
